# Generated by Django 3.2.11 on 2022-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
