# Generated by Django 3.2.11 on 2022-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_letter_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='effect_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='letter',
            name='paper_type',
            field=models.IntegerField(default=0),
        ),
    ]
